# Основные настройки сайта
title: "Правила дорожного движения"
description: "Сайт для изучения правил дорожного движения и тестов на проверку знаний."
url: "https://Anen135.github.io"  # Замените на свой домен
baseurl: "/traffic-rules"  # Можно оставить без изменений
permalink: pretty

# Логотипы для мобильных и десктопных устройств
logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "120px"

# Настройки главной страницы
home:
  limit_services: 6  # Ограничение количества отображаемых услуг

# Коллекции
collections:
  # Коллекция для правил дорожного движения
  rules:
    output: true
    sort_by: title  # Сортировка правил по названию
  # Коллекция для тестов
  tests:
    output: true
    sort_by: date  # Сортировка тестов по дате
    permalink: /tests/:title  # Пример использования тестов с кастомным URL

# Настройки для вывода страниц с контентом
defaults:
  - scope:
      path: ""
      type: "rules"
    values:
      layout: "rule"  # Страница правила
  - scope:
      path: ""
      type: "tests"
    values:
      layout: "test"  # Страница теста

# Стилизация с помощью Sass
sass:
  style: compressed  # Минимизация стилей

# Плагины
plugins:
  - jekyll-environment-variables

# Исключаемые файлы
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md

# Настройки для тестов
test_settings:
  time_limit: 30  # Время на прохождение теста (в минутах)
  max_questions: 10  # Максимальное количество вопросов в тесте

# Настройки для SEO
seo:
  enable: true  # Включить SEO
  title: "Правила дорожного движения и тесты"
  description: "Изучите правила дорожного движения и пройдите тесты на проверку знаний."

# Социальные сети (если нужно)
social:
  twitter: "https://twitter.com/yourusername"
  facebook: "https://facebook.com/yourusername"
  instagram: "https://instagram.com/yourusername"
